import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { Appbar } from "@/components/ui/Appbar";
import type { Metadata } from "next";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title : "Create Next App",
  description : "Generated by create react app"
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
            <Providers>
            <Appbar/>
              {children}
            </Providers>
            <Toaster />
        </body>
    </html>
  );
}
